build:
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - cd docker && docker-compose up --abort-on-container-exit
image: docker
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive